server:
  port: 7771
  servlet:
    context-path: /icat/



icatx:
  versioning:
    savebatchsize: 1000

spring:
  application:
    name: IcatxIdentityGeneration
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  data:
    mongodb:
      host: localhost
      port: 27017
      database: webprotege
      auto-index-creation: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://webprotege-local.edu/auth/realms/webprotege
      client:
        registration:
          keycloak:
            client-id: webprotege
            authorization-grant-type: authorization_code
            scope: openid
        provider:
          keycloak:
            issuer-uri: http://webprotege-local.edu/auth/realms/webprotege
            user-name-attribute: preferred_username

webprotege:
  rabbitmq:
    requestqueue: webprotege-identity-generation-queue
    responsequeue: webprotege-identity-generation-response-queue
    timeout: 60000
    event-subscribe: true
    events-queue: webprotege-identity-generation-events-queue
  readWriteLock:
    timeoutInMillies: 1000
    maxRetries: 5

keycloak-issuer-url: http://webprotege-local.edu/auth/realms/webprotege/protocol/openid-connect/certs
